# Generated by Django 5.0.4 on 2024-07-03 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='file',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_flash_cards',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_multiple_choice',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_summary',
        ),
        migrations.AddField(
            model_name='quiz',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quiz',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='fileKey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='fileName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quizType',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
