# Generated by Django 5.0.4 on 2024-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quiz_file_remove_quiz_is_flash_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
